name: Upload Artifact

on:
  push:

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Confirm files
        run: pwd | ls | echo $GITHUB_WORKSPACE
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: save-to-scrapbook-on-notion
          path: ${{ GITHUB_WORKSPACE }}/save-to-scrapbook-on-notion
