name: Upload Artifact

on: 
  workflow_dispatch

jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: save-to-scrapbook-on-notion
